# Generated by Django 5.0 on 2023-12-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default=1, verbose_name='image'),
            preserve_default=False,
        ),
    ]
